# B

#### Budykova křivka
::: collapsible
Budykova křivka je součástí modelu dlouhodobé hydrologické bilance. Přepodkladem je platnost následujícího vztahu
$$
P_{LT} = Ea_{LT} + Q_{LT},
$$ kde $P_{LT}$ je dlouhodobý roční srážkový úhrn, $Ea_{LT}$ je výška douhodobé roční aktuální evapotranspirace a $Q_{LT}$ je dlouhodobá výška ročního odtoku.

Dle tohoto vztahu je možné vyjádřit douhodobý součinitel odtoku

$$
\frac{Q_{LT}}{P_{LT}} = 1- \frac{Ea_{LT}}{P_{LT}}.
$$
Dále je základním předpokladem platnost následujícího předpokladu
$$
\frac{Ea_{LT}}{P_{LT}} = f (P_{LT}, PET_{LT}),
$$ kde $PET_{LT}$ je výška dlouhodobé roční potenciální evapotranspirace.

Model Budykovy křivky je možné vyjádřit například Schreiberovým modelem
$$
\frac{Ea_{LT}}{P_{LT}} = 1- exp(-AI),
$$ kde $AI$ je index aridity, který je definován jako

$$
AI = \frac{PET_{LT}}{P_{LT}}.
$$



:::

#### Bowenův poměr
::: collapsible
Poměr množství tepla, které zemský povrch předává kombinací molekulární vodivosti a turbulentní výměny do atmosféry a množství tepla, jež se na něm spotřebovává na výpařování vody, se nazývá *Bowenův poměr*. Tento poměr je přímo měřitelný

$$
B = \dfrac{Q_h}{Q_e}
$$ kde $Q_h$ je teplo zjevné a $Q_e$ teplo latentní.

Typické hodnoty bowenova poměru uvádí tabulka [@campbell2000introduction]
:::

